services:
  weather-api-service-a:
    build:
      context: .
      dockerfile: service-a/build/dockerfile
    container_name: weather-api-service-a
    ports:
      - "8181:8181"
    restart: always

  weather-api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: weather-api
    ports:
      - "8080:8080"
    restart: always
